name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate static content
      run: |
        mkdir -p dist
        python -c "
        from ctg_api import ClinicalTrialsAPI, visualize_trial_locations_interactive
        
        api = ClinicalTrialsAPI()
        fig = visualize_trial_locations_interactive(
            api=api,
            search_expr='cancer AND recruiting',
            max_studies=50,
            title='Example: Cancer Clinical Trials Map'
        )
        
        fig.write_html('dist/index.html', full_html=True, include_plotlyjs='cdn')
        "
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true
